### ISSUE TITLE
deps-old short form tests

### ISSUE THREAD

**Issue by Andre-487** [enb-bem/enb-bem-techs#118]
In the deps-old you can declare shouldDeps like this:
```
(['block1', 'block2'])
```

```
('some-block')
```

```
'some-block'
```

But it doesn't represented in tests of the technology. Need to write tests for this deps form.

**Comment by tadatuta** [comment]
@Andre-487 can you suggest a pull request, please?

**Comment by Andre-487** [comment]
I would done it already, but I have not enough time.
