### ISSUE TITLE
mustDeps from own modifier is impossible

### ISSUE THREAD

**Issue by tadatuta** [enb-bem/enb-bem-techs#148]
Looks like it's impossible now to have `mustDeps` from own modifier:

```
$ ls common.blocks/b1/
b1.deps.js

$ cat common.blocks/b1/b1.deps.js
({
    mustDeps: [
        {
            mods:  { m1: 'v1' }
        }
    ]
})

$ enb make
# ...
Error: Unresolved deps:
b1 <- b1_m1_v1
b1_m1_v1 <- b1, b1_m1
b1_m1 <- b1
```

// cc @blond @incrop

**Comment by tadatuta** [comment]
BTW,
```js
({
    mustDeps: [
        { elems:  ['e1'] }
    ]
})
```
works fine.

**Comment by incrop** [comment]
@tadatuta I think this is not a bug, you have a circular `mustDeps` issue here.
Modifier should _modify_ the block, therefore block must be declared before its mods.
In `deps` tech this is enforced by [adding](https://github.com/enb-bem/enb-bem-techs/blob/master/lib/deps/deps-resolver.js#L206) block to `mustDeps` for mod. This is how it always worked (check [this commit](https://github.com/enb-make/enb/blob/e825ff0876cc71202e74bdf13a227c4e7dc5ed82/lib/deps/deps-resolver.js#L86) from 2013).
Noteworthy, `deps-old` tech allows you to have `mustDeps` from own modifier.

**Comment by tadatuta** [comment]
I understand the idea but still I used to use such possibility with `deps-old` at least for 2 reasons:
1. To override some styles of a `_theme` from a library on project level. It's quite safe when you know what you're doing as most likely there's no CSS for block without theme modifier.
2. To set some defaults for non-BEM modules. E.g. in `m1_lang_ru.js`:
```js
m1.defaults.lang.ru = {/* ... */};
```
And then I can initiate an instance of `m1` in `m1.js`.

Both of the cases are quite ugly but still they were possible when really needed.

**Comment by Guria** [comment]
+1, I don't like an implicit deps from block.

**Comment by tadatuta** [comment]
I asked @veged, he agrees that it's a bug

**Comment by blond** [comment]
@tadatuta Looks really like a bug. The question is whether you can fix it without breaking habitual behavior.

**Comment by blond** [comment]
This problem is also relevant for elem mods:

```js
({
    mustDeps: [
        {
            elem: 'elem', mods:  { m1: 'v1' }
        }
    ]
})
```

```
Error: Unresolved deps: 
block__elem <- block__elem_mod-name_mod-val
block__elem_mod-name_mod-val <- block__elem, block__elem_mod-name
block__elem_mod-name <- block__elem
```

**Comment by Guria** [comment]
is https://github.com/bem/bem-forum-content-ru/issues/182 relevant to this issue?

**Comment by blond** [comment]
@Guria, I think that this is another problem.
