### ISSUE TITLE
deps: Parse mods as array

### ISSUE THREAD

**Issue by tadatuta** [enb-bem/enb-bem-techs#159]
Not sure if it should work at all but in `bem-componens` [there's](https://github.com/bem/bem-components/tree/0a060e7dea45790d162fdbb1f09e08d3e8d705cb)
```js
shouldDeps : {
    mods : ['disabled', 'focused'],
}
```
which results in
```
  'input_0',
  'input_1',
  'input_0_disabled',
  'input_1_focused'
```
now.

**Comment by tavriaforever** [comment]
I never saw deps with mods writing in array way, it`s strange.

**Comment by blond** [comment]
duplicate of #113
