### ISSUE TITLE
Support dots in modifier values

### ISSUE THREAD

**Issue by incrop** [enb-bem/enb-bem-techs#184]
Currently levels tech treats everything after first dot in file name as [extension](https://github.com/enb-bem/enb-bem-techs/blob/v2.0.1/lib/levels/level.js#L75).
Thus, mod values with `.` are prohibited.
They were possible in [bem-tools](https://github.com/bem/bem-bl/tree/support/2.x/blocks-desktop/i-jquery/__core/_version).

**Comment by blond** [comment]
I do not think you have to want it. We've already discussed it here: https://github.com/bem/bem-naming/issues/39.

**Comment by incrop** [comment]
Yeah, on a second thought, one should not give BEM entity a name that is not a legal CSS class.
Will replace dots with `-` in deps and filenames, and leave dots in templates for compatibility.
