### ISSUE TITLE
Как из deps-old перейти на deps?

### ISSUE THREAD

**Issue by Immuzov** [enb-bem/enb-bem-techs#187]
Не собираются зависимости, пробовал как в примерах из документации, не получилось.
Сам make.js ([gist](https://gist.github.com/Immuzov/0394f62255430c773637#file-make-js-L92-L148)).

## npm зависимости:
```
    "enb": "~0.17.2",
    "enb-bem-techs": "~2.1.0",
    "enb-bemxjst": "~2.1.0",
    "enb-borschik": "^1.1.1",
    "enb-js": "~1.1.0",
    "enb-modules": "~0.2.0",
    "enb-stylus": "~2.1.0",
    "enb-bundle-postcss": "tadatuta/enb-bundle-postcss",
```

Обсуждение началось [здесь](https://github.com/enb-bem/enb-bem-techs/issues/18#issuecomment-149033800). Что я упустил?

@tadatuta

**Comment by tadatuta** [comment]
Теоретически для перехода должно быть достаточно буквально заменить `depsOld` на `deps`, все остальные изменения напрямую со сборкой депсов не связаны. В частности в качестве примера можно использовать [project-stub](https://github.com/bem/project-stub/blob/bem-core/.enb/make.js#L43).

Чтобы разобраться, хорошо бы посмотреть целиком на код, на котором воспроизводится проблема.

**Comment by Immuzov** [comment]
@tadatuta, [выложил](https://github.com/Immuzov/lappse/tree/develop) (develop ветка).
```
npm install && npm run start
```
Дальше можно `gulp` для вотчинга изменений или вручную `npm run views-compile` из корня. Здесь рабочая версия с технологией deps-old, проверял работает технология или нет на файле `/frontends/src/bundles/desktop.bundles/index/index.deps.js`.

**Comment by blond** [comment]
@Immuzov, @tadatuta проблема решилась?

**Comment by Immuzov** [comment]
Нет, но уже не актуально.
